version: "2.3"
services:
    detic_2004_ws:
        build:
            context: "builddir"
            dockerfile: "Dockerfile_rs435"
        container_name: detic_2004_container
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
            # to transport X11 application window
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - ROS_HOSTNAME=localhost
        volumes:
            # for USB devices
            - /dev:/dev
            # to tansport X11 application (require xhost local:)
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            # ros catkin dir
            - ../catkin_ws/src/detic_ros:/catkin_ws/src/detic_ros
        privileged: true
        tty: true
        network_mode: host
        command: bash -c "source /opt/ros/noetic/setup.bash && catkin build -DPYTHON_EXECUTABLE=/usr/bin/python3 && /catkin_ws/src/detic_ros/install.sh && bash"
    detic_1804_ws:
        build:
            context: "builddir"
            dockerfile: "Dockerfile_k4a"
        container_name: detic_1804_container
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
            # to transport X11 application window
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - ROS_HOSTNAME=localhost
        volumes:
            # for USB devices
            - /dev:/dev
            # to tansport X11 application (require xhost local:)
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            # ros catkin dir
            - ../catkin_ws/src/detic_ros:/catkin_ws/src/detic_ros
        privileged: true
        tty: true
        network_mode: host
        command: bash -c "source /opt/ros/melodic/setup.bash && cd /catkin_ws && catkin build && bash"
